; 由 ESP-AI Studio 生成的 PlatformIO 工程
; 本地编辑，云端编译（GitHub Actions：ubuntu + pio run）

[env:teensy40]
platform = teensy
board = teensy40
framework = arduino
build_flags = -DLED_BUILTIN=13
upload_port = /dev/ttyACM0
upload_protocol = serial
upload_fqbn = teensy:teensy40
monitor_speed = 115200
